### ISSUE TITLE
Update actions/checkout in GitHub Actions to v3

### ISSUE THREAD

**Issue by martinmoene** [nonstd-lite/nonstd-lite#63]
See [expected-lite, PR45](https://github.com/martinmoene/expected-lite/pull/45).

Progress:

- [x] lest
- [ ] active-lite
- [ ] any-lite
- [ ] atomic-lite  (WIP)
- [ ] bit-lite 
- [ ] boolean-lite
- [ ] byte-lite 
- [x] expected-lite
- [ ] invoke-lite 
- [ ] jthread-lite 
- [ ] observer-ptr-lite 
- [ ] optional-bare 
- [ ] optional-fun-lite (no tests)
- [ ] optional-lite
- [ ] ring-span-lite 
- [ ] scope-lite
- [x] span-lite
- [ ] status-value-lite 
- [ ] string-lite (WIP)
- [x] string-view-lite
- [ ] type-lite 
- [ ] value-ptr-lite 
- [ ] variant-lite

**Comment by striezel** [comment]
This issue is a duplicate of https://github.com/martinmoene/nonstd-lite-project/issues/70, and most (all?) of the other projects have been handled there, so this issue here can be closed.

**Comment by martinmoene** [comment]
't has been a while :)

thank you!
