### ISSUE TITLE
Remove Travis configuration and badge

### ISSUE THREAD

**Issue by martinmoene** [nonstd-lite/nonstd-lite#65]
Inspired by [_lest_ PR 74](https://github.com/martinmoene/lest/pull/74).

Actions:

- Delete `.travis.yml`
- Remove Travis badge from `Readme.md`

Plan:

- [x] lest
- [x] nonstd-lite-project
- [x] any-lite
- [x] atomic-lite
- [x] bit-lite
- [x] boolean-lite
- [x] byte-lite
- [x] expected-lite
- [x] invoke-lite
- [x] jthread-lite
- [x] observer-ptr-lite
- [x] optional-bare
- [x] optional-lite
- [x] ring-span-lite
- [x] scope-lite
- [x] span-lite
- [x] status-value-lite
- [x] string-view-lite
- [x] type-lite
- [x] value-ptr-lite
- [x] variant-lite

Other:

- optional-fun-lite
- string-lite
- active-lite
- rpc-lite

**Comment by striezel** [comment]
The list above also contains `invoke-lite`, but I created no PR for that project, because the Travis CI badge has already been removed there: https://github.com/martinmoene/invoke-lite/commit/68dce1b3a1db9e28fa52ccf251a50b3aba09bd7c

**Comment by martinmoene** [comment]
Many thanks @striezel :)
