### ISSUE TITLE
Update actions/checkout in GitHub Actions to v3

### ISSUE THREAD

**Issue by martinmoene** [nonstd-lite/nonstd-lite#70]
See [bit-lite PR 3](https://github.com/martinmoene/bit-lite/pull/3).

Plan:

- [x] lest (NA)
- [x] active-lite
- [x] any-lite
- [x] atomic-lite
- [x] bit-lite
- [x] boolean-lite
- [x] byte-lite
- [x] expected-lite
- [x] invoke-lite
- [x] jthread-lite
- [x] observer-ptr-lite
- [x] optional-bare
- [x] optional-lite
- [x] optional-fun-lite
- [x] ring-span-lite
- [x] scope-lite
- [x] span-lite
- [x] status-value-lite
- [x] string-lite (NA)
- [x] string-view-lite
- [x] type-lite
- [x] value-ptr-lite
- [x] variant-lite
- [x] nonstd-lite-project

Other:

- rpc-lite

**Comment by striezel** [comment]
Just for information: Some of the projects mentioned in the plan above have no pull request, but for some the corresponding change was already made earlier:

* expected-lite: https://github.com/martinmoene/expected-lite/commit/8c05f5539fd21b7595c2eb1d3763322a5ea72ae3 / https://github.com/martinmoene/expected-lite/pull/45
* span-lite: https://github.com/martinmoene/span-lite/commit/dbb484f6c2060b41afa55653dec99b228013a813 / https://github.com/martinmoene/span-lite/pull/75
* string-view-lite: https://github.com/martinmoene/string-view-lite/commit/f7aca36f5caa05e451f6887aa707df89197e6de6 / https://github.com/martinmoene/string-view-lite/pull/51

**Comment by martinmoene** [comment]
@striezel Thanks again :)

**Comment by striezel** [comment]
> @striezel Thanks again :)

You're welcome. After all, we C++ users have to support each other. :)

And as a nice side effect this is a new personal record for the number of pull requests per day. :smile:
